import * as esbuild from 'esbuild';
import fs from 'node:fs';import path from 'node:path';
const root=process.cwd();
const result=await esbuild.build({entryPoints:['review/entry.tsx'],bundle:true,write:false,minify:true,jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},alias:{'next/link':path.join(root,'review/navigation.tsx'),'next/navigation':path.join(root,'review/navigation.tsx')},loader:{'.woff2':'dataurl'}});
let js=result.outputFiles[0].text;
const mime={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2'};
let embedded=0;
js=js.replace(/(["'])(\/(?:espacios|lmt|posters|catalogue)\/[^"']+|\/(?:cube-logo-white|cube-hero)\.png|\/sony-partner\.jpg)\1/g,(match,q,url)=>{const file=path.join(root,'public',url);if(!fs.existsSync(file))return match;embedded++;return JSON.stringify(`data:${mime[path.extname(file)]};base64,${fs.readFileSync(file).toString('base64')}`)});
const font=fs.readFileSync('public/fonts/manrope-latin.woff2').toString('base64');
const cssFiles=fs.readdirSync('out/_next/static/css').filter(f=>f.endsWith('.css'));
let css=cssFiles.map(f=>fs.readFileSync('out/_next/static/css/'+f,'utf8')).join('\n');css+='\n'+fs.readFileSync('src/app/editorial.css','utf8');
css+=`@font-face{font-family:Manrope;src:url(data:font/woff2;base64,${font}) format('woff2');font-weight:200 800;font-display:swap}:root{--font-inter:Manrope}`;
const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>CUBE Post — Propuesta para revisión directiva</title><style>${css}</style></head><body><div id="root"></div><script>${js.replace(/<\/script/gi,'<\\/script')}</script></body></html>`;
fs.mkdirSync('review-output',{recursive:true});fs.writeFileSync('review-output/CUBE-Post-Revision-Directiva.html',html);console.log(JSON.stringify({embedded,bytes:Buffer.byteLength(html)}));
